# Use the official MySQL server image
FROM mysql:9.0.0

# Set the root password for MySQL
# Note: You should replace 'your_password' with a secure password
ENV MYSQL_ROOT_PASSWORD=12345

# Expose the MySQL port
EXPOSE 3306:3306

# Start the MySQL server
CMD ["mysqld"]
